const numberOfPoems = 42;

const textArray = ["zeroDoesntExist",
    "there was a man who was curly <br> with effort he also burly <br> he fought back against coomers <br> no patience with boomers <br> of spirits he was a consoomer <br> <br> m'bosso he was a grand lad <br> he could fuck up a big ass brad <br> with a big ass meat stick <br> dick is soup-can thicc <br> he could spitroast even great chud <br> <br> asses to asses, dusk to dusk (?) <br> a dick like an elephant tusk <br> to spitroast a bitch <br> to scratch a great itch <br> he fuck like the great elon musk",
    "ode to strr: a dagger or rapier perhaps? <br> hark! no! that would make us dex-fags! <br> i have one rule brr <br> i spend all souls on strr <br> big pecs = big check and fat stacks",
    "i ain't never seen no swine like them there pigs <br> ain't swindling no kindling, throwing pearls for pigs <br> louisana pedo don't need door <br> he smash the walls, and breaks you like a twig <br> proud mullet wearin redneck, but aint no hick <br> sees doors of perception, minds drifts ashore <br> consooms copious kegs, coors light galore <br> a southern zarathustra, moonshine he swigs <br> black cop be like, 'missing persons, lol, sike!' <br> he dont believe, so aint no reprieve, for steve <br> he gon' be dead, made into cornbread <br> pedos and swamp things i with my knife strike <br> it's raining chainsaws in the quoral quee <br> the quota of beer <br> oh what a relief <br> we'll reach it <br> just grind up the dead",
    "his visage beastly was a snarlin' <br> he found himself a cute darlin' <br> to plow with his stick <br> until he was sick <br> with his dick he was himself harmin' <br> <br> there once was a dog from the sea <br> a dank man, everybody can see <br> he completed uncharted <br> 'tis so retarded <br> but based and redpill'd stay'd he <br> <br> there once was an african dog <br> who fearlessly braved the boss-fog <br> he challeng'd the boss <br> without purple moss <br> and never gave the singlest of fuck",
    "covertly concealed his constipation <br> coagulated crap in colon creepeth <br> and loosened so soon the septic sewage seepeth <br> septuangenarian stool soon sloshed the nation <br> nary a nook or neck of wood withstood contamination <br> as allans anal abomination did deepenth <br> so did sleazy sickos sickly sleuzen <br> and showered the shower of shit in sick adulation <br> ravenously did they revel in his rectal refuge <br> posthaste these perverse peckerwoods politizises <br> looking to legitimize: leave lort an elected official <br> orificial offering ornate in haute cauture <br> mayhaps this hubris might materialize <br> and soon much sicker shit was shat from the [redacted] <br> the humbled heretics hark'd and drowned in divine manure",
    "did the axe done good? yes it done did <br> doth the hack scum schemeth? some say schemem. <br> you cucks you coom with whitegray semen <br> you'll end in deepest hell, the darkest pit <br> where devils will on your cock lava spit <br> where cucks hath made sure you get no seamen <br> drip drop, slip slop, woop-de-scoop-de-meme'in <br> knick knack paddy whack, lickety-split, hacks eat shit <br> new-york city gritty comity, pity the fool that <br> get pants shat by madlad, some say ladm <br> textin' and drivin' down mulholland drive <br> thats why i take the 405, sick hat <br> fuckboy cucks, i take a bat and bat 'em <br> ice cold, bad cats, when i rap, it's jig'n jive",
    "fuck the coom-freaks, coomin' straight outta underground <br> the monk-e with more dope than eazy-e <br> blink and you'll miss it, big-biz gorilla biscuit, see? <br> bonobo in a suit, pro bono, the count <br> cook the books on the coconut-amount, white-wash bananas by the pound <br> humility must be in lost and not found, you see, g? <br> the fate of man eventually, will be determined by the flows of chimpanze causality <br> hitman harambe racking up a headcount <br> big dick monkey samba flatten bipedal bitches <br> clap cheeks, stack checks, rhymes dirtier than herpes but harder to catch <br> bonobo bimbo bitches blow benis <br> we got the damn monkey-gene, you're a hack, man. gene [redacted] here snitches <br> imprison the humans, and never open the latch <br> primate power-cleaners, chimpanzee-curl-machines <br> howler-monkeys hack homo sapiens-peeners",
    "imma be honest, im kinda retarded <br> went to take a shit but only farted, yet i rock on <br> a stiffy appears, and i summon the porn <br> a rock hard hard-on, my coom-stick larded <br> intergalactic vampires departed <br> from outer space, the moon call'd orion <br> fake school shootings, get my thought on <br> gay frogs, you lame fucks, just getting started <br> built like gorilla, mind like a chimp <br> affinities in tactical hygiene <br> the destroyer of thug-scum with mad swipes <br> i deep dick statists and wealthfare simps <br> obamas from nigeria, hillarys clit smells like sardines <br> flush her down pipes <br> shit on the kikes <br> finish the show with combat wipes",
    "from the french-frie-fryer, rose an itchyoid figure <br> drenched in trans-fat sweat, it left an itchy trail <br> cheddar-tentacled, clutching paper cup grail <br> sodastream ichor filled with bitch vigor <br> as the orchard of the obese overlord grows bigger <br> grilled cheese comes across the sky, nuggets fall like hail <br> in bondage humanity quivers, from his chickenfried flail <br> man's back is striped like beefs on a grill, sicker <br> more putrid by the hour, the gut of man grows thiccer <br> with every happy meal comes a forced smile <br> force fed franks, the mouth of a man of ghastly grimace <br> ghoulishly the god of gouda, finger on the trigger <br> hits a k-o with the mayo, better lay low while <br> row row with the fat fuck b.o. <br> the greasy fingers of providence mold mans soul like play-doh",
    "shall i compare thee to a summers wine? <br> dost not that tentacled thing thine loins moisten <br> figen shot is a vile and toxic poison <br> your rhyme's the opposite of very fine <br> oh, these incomparable invertebrates <br> a man did scam a dyke; what sham! fuck him! <br> you write such lines, the puke will not subside <br> upon my brain rupi kaur grates <br> 'copacetic cephalopod cunts' hark'd jim <br> i love milk and honey, i have no pride",
    "there once was a man who was boss <br> he smok'd fools without a big fuss <br> he's one of the best <br> he has a big chest <br> he'll wreck you if you get cross <br><br> there once was a jolla with a dolla <br> a gentleman and a good scholar <br> he fuck'd with the best <br> and put 'em to rest <br> and mopped the floors without holla <br><br> christopher is a good fella <br> a good natural born killa <br> a real good nigga <br> she don't like it bigger <br> you won't find a bugger who's chiller",
    "there once was a chaddest of chads <br> o', he was the laddest of lads <br> with the maddest of knowledge <br> from byrgenworth college <br> pappa g is the best of dads <br><br> his sideburns were mighty and bushy <br> he had a big waifu plushie <br> he fucked up the dex-fags <br> with hunters-axe-bitchwax <br> he impal'd them right in the tuschy <br><br> when 'gherman the creep' came a knockin' <br> pop gaz put his axe in his noggin <br> at first he was fucke'd <br> but then he him cuck'd <br> he gherman gave a good cockin' <br><br> there once was a man who transform'd <br> by poppa and momma was scorn'd <br> he was a fur venerate <br> an utter degenerate <br> his head with a hat he adorn'd",
    "i go gorilla, a sick killa, shit in your vanilla <br> iller than a chimp on a hill 'a dead pimps <br> hammer curling harambe halving the half life of simps <br> breaking backs like bane, hands like a tiller <br> call me ted munky, the twisted simian serial killer <br> my banana splits your ass, shit's bananas, your life's a glimpse <br> king kong wayne gacy, i get off tearin your head off, and feed it to chimps <br> bombing the loo like im ted kadchimpsky <br> boxing kongo killer in the ring of <br> the btk: banana, torture and killin, the beheading, chin-checkin ape villain <br> the silverback with endless gold, 3-point your head from a free throw <br> half lenin, half kimbo: comrade ape illich ulyanov <br> redistribute this chimp dick to all you hoes seed-tillin' <br> and just by the way <br> this ape drinks the whey <br> this massive gorilla's doin' blow",
    "why always zoe on the fookin phone! <br> why always boris, when name is sergei <br> she don't need no man, kima greggs is bae <br> hey! sergei: my name isphone please tell my mom <br> this is the ore, these are the bones <br> hillbillies and undeads, this shit we slay <br> we will our resources conserve, oy vey <br> balding men and old crones <br> by the cock of tom jones <br> we'll fist fuck all the swamp thing clone <br> mystery lines, lost forever to time <br> obscure scripture, 'at the party, richter' <br> discerning the undiscernible text <br> 'you're next to be fried, the condiment fits the mccrime' <br> the burger king(tm) manager, i dick'd her <br> she sent me a sext, i shouldnt have read <br> i went insane when i read the mcscripture",
    "uncanny valley, mother of a whore <br> leif imitates fart, a flatulent frenzy <br> then juggle the jizzom, and jack off some more <br> wish for a fleshlight, but alas i'm poor <br> so i strangle my stiffy until it goes bendy <br> i'm dissappointing a wench named wendy <br> i swear it's no lie, i creamed 'tween her thighs, made a fleshy smore <br> despite the fucking, my testies be throbbing <br> like some obelisk reaching the skies, and <br> peeking pubescently through voluptous clouds <br> the girth of my rod leave bitches sobbing <br> my omnipotent pecker, and pineal gland <br> unbearably loud i coomed on my couch <br> when i saw jenna haze <br> i was left in a daze <br> and died with my peener ablaze",
    "harambe the ape went a wreckin' <br> with chokeholds and a deep dickin' <br> stuck it to the honkys <br> an activist monke <br> civil rights activist pimpin' <br><br> there once was an ape from ashina <br> who massacred the lit-his cantina <br> he took out nana <br> ate a banana <br> laughed like a manic hyena <br><br> there once was a monke uprising <br> lifestyles so very enticing <br> stab humans with spears <br> they rip off their ears <br> a super weapon derising",
    "pop fat souls to increase your swole, hoebag <br> crank that soulja boy bologna smoker <br> if she don't crank it, then you must choke her <br> smoke huge tokes of Womacks nutsack <br> a big schlong thicker than a monster can <br> a rectum awaiting great punishment <br> a wreckening reckoning: bumhole banishment <br> the kikes and dykes, they conjureth a plan <br> 'returneth ron howard from whence he coometh' <br> let him direct the shit from shinola <br> the menacing mindwaves sent through the tube <br> summons the boomer, from darkness he loometh <br> like simmons he zoometh in rusty skoda <br> to cream all his corn in thine ass with no lube",
    "",
    "before the earth was young, the snake was born <br> a chad since birth, t'was swole of gun. such stud <br> snakes ask'd his brothers: 'wherefore art thou coom?' <br> we came from thy mum; the seed all forlorn <br> to be then men to rule the realms of porn <br> amongst them, a chosen one: 'arch-chud' <br> his name: larry snakes. his testicles bloom'd <br> bloom'd they did, women swoon'd; love reborn, and: <br> five-finger fist fucks, a tongue-punch'd fartbox <br> effluviate thousandfold, vaginae lined with gold <br> snake dipped deep, he got the clap, sick he art <br> wicked wenches: he wrecketh all-his cocks <br> whenceforth flowed wondrous venoms, viscous and cold <br> he bid farewell, from heaven fell, a fart",
    "primoridal pork rinds portend impending doom <br> fat bacon fizzling before the earth was young <br> laid the savoury foundation, of mans eventual swan-song <br> born to wear a fat-layer, eternally consoom <br> under cooming moon, the night is long <br> half a soggy pie in a bleeding sky, forlorn <br> for man sees not diets, but only endless fries, and soon <br> planes will converge; mcinfernal realm and world of man conjoined <br> to form a meal unreal in calories <br> seasoned with suffering, an inhuman mcoffering <br> to make mcmanus the new mcmenace, and life avoid <br> unhole hands to unleash the hambyss, mcdecree <br> a mcplague will mcspread <br> bread and mcfry the dead <br> an unholy sammich <br> for father mcmanus <br> a final satanic mcstuffening",
    "10 whiskeys deep, forbidden mcscripture: <br> 3 fingers deep, the hidden mctrigger <br> hot button orifice, don't let the moment flicker <br> the 2am rimjob you must endure <br> prostate propulsion; paramount expenditure <br> no unleashment of white stickiness thicker <br> bimbo bitches, there just aint no thiccer  <br> kimbo crush snitches, a rightous venture <br> suck a fat schlong, dick like king kong <br> cooming fat loads from that fat mcdingdong <br> sling a sick schlong, big guy's mccurlyfry <br> sit on this,split your thong, sick your last [redacted] <br> 'im gunna fuck yer' mum' said the mcbritbong <br> the man with the mask? for you: big guy",
    "incel epic: <br> there once was a cuck in a town <br> on tiktok they call'd him a clown <br> he jizzed in a sock <br> but wanted some fuk <br> but all that he got was a frown  <br>  <br> titaniteslabepic.mp4: <br> i press'd out a titanite slab <br> like khalifa i did a dab <br> i blew out the shitter <br> i don't know what her hit her <br> i took a dumb through her leg-gap <br>  <br> snakes, chad snakes: <br> there once was a larry named snakes <br> on wenches he is cummin' lakes <br> they gargled' his jizzom <br> but read no john grisham <br> his penis it really much aches",
    "awakest thou nightly, sweat drenched and ketchup-[redacted] <br> dost thine heart pump chili-mayo through thine veins? <br> forsake thine volition, let trans-fat take the reins <br> a life without denny's is not worth saving <br> veins bulging with syrup: existentially sating <br> sanity fading, deep fried chicken reigns <br> thine fitness forsaken, you diet in vain <br> listless puppet of waffles, only mcserfdom remains <br> to be a footsoldier for burgerkings plans <br> porkchops pulling your strings, fish-stick sinew <br> thine flabbyness flaps and fat-folds unfurl <br> a wide marionet in a coagulating dance <br> from deep-fry spawning pit, you are born anew <br> into a spiraling onion ring, a brave new mcworld",
    "",
    "through hardship for phone, was great friend andrei <br> a jolly slav fellow with a soviet bellow <br> about pones beastliness he was mellow <br> a beast slayer emergeth: van sergei! <br> a rightous christian, he hath no love for the geh <br> he doesn't want men to others' cocks blow <br> his homo hate only matched by his ire for beasts from below <br> this by the laws of fate he must clash with phone and his breh <br> with whip in hand, he prepares for hate crime <br> his malformed mind; a twisted simp zealot <br> the aryan race he wishes to develop <br> 'i'm coming for you, you're all outta time!' <br> 'that sounds pretty gay' said phone with a smile <br> with power of mouth <br> andrei goes south <br> and sergeis cock he will envelop",
    "so sergei got to gargelin' andreis appendage",
    "",
    "",
    "",
    "30",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "40",
    "",
    "42"
]

let poemsArray = [];

for (let i=1;i<43;i++){
    poemsArray.push(
        {
            poemNr: `${i}`,
            poemSrc: `./mcdatabase/poem(${i}).jpg`,
            poemText: textArray[i]
        });
}

const passagesArray = ["he was a fur venerate / an utter degenerate", "they gargled the jizzom / but read no john grisham", "limp dick doug dimmadomes get sliced like cabbage", "i have one rule brr / i spend all souls on strr / big pecs = big checks and fat stacks", "to plow with his stick / until he was sick", "drip drop, slip slop, woop-de-scoop-de-meme'in / knick-knack paddy whack, lickety-split, hacks eat shit", "big dick monkey samba flatten bipedal bitches / [..] / bonobo bimbo bitches blow benis", "hillary's clit smells like sardines / flush her down the pipes / shit on the kikes / finish the show with combat wipes", "a man did scam a dyke; what sham! fuck him!", '"copacetic cephalopod cunts" harkd jim', "call me ted munky, the twisted simian serial killer [..] bombing the loo, like i'm ted kachimpsky", "hey! sergei: my name isphone please tell my mom", "unbearably loud i coomed on my couch / when i saw jenna haze, i was left in a daze / and died with my peener ablaze", "so i strangle my stiffy until it goes bendy / i'm dissappointing a wench named wendy", "pop fat souls to increase your swole, hoebag", "a wreckening reckoning: bumhole banishment", "his name: larry snakes. his testicles bloom'd / bloom'd they did, women swoon'd; love reborn and: / five-finger fist fucks, a tongue-punch'd fartbox", "seasoned with suffering, an inhuman mcoffering", "there once was a cuck in a town", "i blew out the shitter / i don't know what hit her", "with whip in hand, he prepares for hate crime", "the untimely termination of fellatio gave the erstwhile guzzler leverage", "you're left cooming in your room in a jizz salto", "blow your rectal trumpets gabriel", "to poke and prod with massive, pulsing rod", "eldritch effluviate engulfed england / rich royal rightous racists repress'd rembrandt / painting purple pompous painful ass", "'to check yourself before you wreck yourself is sound advice' hark'd snakes and took a shit", "and met a lad nam'd lee who was to be / a cocksman of the highest order", "paul bunyuns bunion for the rings of mconion", "angela merkel nukes the ukranians", "it rot, then smell'd, then he said: lets have fun / we'll have loads of fun with rape and pillage", "a kike he drew a knife to fight, and lurk", "the world is dark and black with death, it sucks / i hate these fucking cooming zoomer cucks", "'laughing, larry cut of his head, then said / you're dead, you fuck, i got the balls of gods' / while ye coomers were masturbating, i be decapitatin'", "my pleasure is my dick in a mouse trap", "'o, ye old god of cod: ye hath harness'd / the power of the ass' stated larry", "finger much but hole? dat ass", "he took their wives, the chink, the horse the coon / he met zizek, he sniff'd a sea of coke", "shaking his fist at the paleblood sky, he said: / 'with slugs, and his fav'rit weapon: pencils / from the depths of hell, i relieve at thee my guts", "follow the path of living[larry] snakes", "all work and no play makes jack a mad breh"];

export { textArray, poemsArray, passagesArray, numberOfPoems };